### ISSUE TITLE
Changing the font in nvim-pygtk3

### ISSUE THREAD

**Issue by ronisbr** [rliang/nvim-pygtk3#1]
Hi!

First, congratulations! Very nice app 👍 

I'm wondering if it is possible to change the default font of this app.

Thanks,
Ronan

**Comment by rliang** [comment]
Hi, thanks for the comment! :+1: 

f488f0d5c8ecd163123d5f0f1c8d4af02fc2fc27 should allow changing the font through Tweak Tool, `gsettings`, `dconf` etc.
