### ISSUE TITLE
doesn't respect background from config file

### ISSUE THREAD

**Issue by cinghiopinghio** [rliang/nvim-pygtk3#2]
Great project,

while using it I discovered that the gui doesn't respect the background I set in the config files.
In both `ginit.vim` and `init.vim` I set:
``` vim
set background=dark
set bg=dark
```
but the gui starts always with light bg! (anyway I think it should be enough to set it in `ginit.vim`)

If once started I set it manually `:set bg=dark` it switches to dark bg as expected.

**Comment by rliang** [comment]
Hi, thanks for the heads-up. Not really sure what's causing that problem. Did you try it with an empty `init.vim` except for those lines?

Since it works after startup, a temporary workaround could be using `autocmd VimEnter * set bg=dark` instead.

**Comment by cinghiopinghio** [comment]
I found the problem: I set 
``` vim
highlight Normal guibg=NONE ctermbg=NONE                                        
highlight nonText guifg=#787878 guibg=NONE ctermfg=243 ctermbg=NONE  
```
just after setting the background to have a nice transparency on the console.
This sadly take over the `bg` settings.

Anyway, settings defined in `ginit.vim` get completely ignored... is there a motivation for this?

**Comment by rliang** [comment]
Can't really see anything in the code that changes how nvim deals with `ginit.vim` :(

**Comment by cinghiopinghio** [comment]
I've investigated a bit and there is an open issue in `neovim`: https://github.com/neovim/neovim/issues/3656.

In [Neovim-qt](https://github.com/equalsraf/neovim-qt) they temporally solved this by calling `runtime! ginit.vim` directly on their code: [see line 141](https://github.com/equalsraf/neovim-qt/blob/26a6b434c53472e8b8dc41f208c06f59cd9f60e9/src/gui/shell.cpp#L141)

I don't know if you want to follow their approach.
