### ISSUE TITLE
send commands to nvim

### ISSUE THREAD

**Issue by cinghiopinghio** [rliang/nvim-pygtk3#3]
Hi,

Is there a way to send command line arguments to nvim (I'd like to send commands such as `-c <command>`)?

Thanks.

**Comment by rliang** [comment]
Hi,

I believe all given command-line arguments should be already being passed as-is to nvim.

**Comment by cinghiopinghio** [comment]
I don't know why I wasn't able to make it work... indeed it works like charm out of the box.

Thanks
