### ISSUE TITLE
White frame around terminal

### ISSUE THREAD

**Issue by sebastien** [rliang/nvim-pygtk3#7]
There is a white frame around the Vte widget, which seems made of two part:

1) A white 1px frame border that is always there
2) A variable right and bottom border that grows/shrinks as the window is resized (the bottom border also happens with Gvim), the border becoming 0px when the width/height is a multiple of a character width/height.
![screenshot from 2017-06-16 08-40-27](https://user-images.githubusercontent.com/14598/27227082-f0b00d88-526f-11e7-8c23-fe2721a372ae.png)

**Comment by rliang** [comment]
Hi, have you tried `set background=dark`?
