### ISSUE TITLE
Shebang crashes over virtualenv's

### ISSUE THREAD

**Issue by oliveiraev** [rliang/nvim-pygtk3#8]
https://github.com/rliang/nvim-pygtk3/blob/48787256e64d698d58d087d91c1dedd8b648c28d/nvim-pygtk3#L1 breaks requirements whithin virtualenvs:

```
No module named gi
```

The best solution is make [Makefile](../blob/4878725/Makefile) replace the first line with detected python.

**Comment by rliang** [comment]
Hi,

I'm not too familiar with virtualenvs, how should I do it? A pull request would be welcome too.

**Comment by oliveiraev** [comment]
```pip install --user virtualenv``` or ```sudo pip install virtualenv```

```virtualenv $HOME/sample-virtualenv```

```source $HOME/sample-virtualenv/bin/activate```

```nvim-pygtk3```

I'll think about several-different-possible-environments fix.
